#!/usr/bin/env php
<?php

define('SLOWFOOT_START', microtime(true));
define('SLOWFOOT_BASE', __DIR__);
// error_reporting(E_ALL);
require __DIR__ . '/vendor/autoload.php';

require __DIR__ . '/vendor/cwmoss/slowfoot-lib/src/command.php';
